apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - command:
        - ls
        - -a
        image: gcr.io/joonkim-experiments/tfx_dev:latest
        name: controller
